annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: 2.2.2
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: An Application dashboard and launcher
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/heimdall
icon: https://i.imgur.com/mM4tcO5.png
keywords:
- heimdall
kubeVersion: '>=1.16.0-0'
maintainers:
- email: jeff@billimek.com
  name: billimek
name: heimdall
sources:
- https://hub.docker.com/r/linuxserver/heimdall/
- https://github.com/linuxserver/heimdall
version: 8.4.2
